// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBevhnB7WArQl6rMA2CJg9ITZxMrwdo-bo',
    appId: '1:826620575400:web:bcca697f92bd7b7da1cc9d',
    messagingSenderId: '826620575400',
    projectId: 'gestor-notas-78d5b',
    authDomain: 'gestor-notas-78d5b.firebaseapp.com',
    storageBucket: 'gestor-notas-78d5b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpRRGwHLrcehSmGdaIy9CuBQQQImvDBOo',
    appId: '1:826620575400:android:20bcd32de287f7c1a1cc9d',
    messagingSenderId: '826620575400',
    projectId: 'gestor-notas-78d5b',
    storageBucket: 'gestor-notas-78d5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhAFIFpqiOlBQTs3iqNdQo5SwfKnZdNMQ',
    appId: '1:826620575400:ios:1bcc62178088378ca1cc9d',
    messagingSenderId: '826620575400',
    projectId: 'gestor-notas-78d5b',
    storageBucket: 'gestor-notas-78d5b.firebasestorage.app',
    iosBundleId: 'com.example.ldsw37BasesDeDatos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhAFIFpqiOlBQTs3iqNdQo5SwfKnZdNMQ',
    appId: '1:826620575400:ios:1bcc62178088378ca1cc9d',
    messagingSenderId: '826620575400',
    projectId: 'gestor-notas-78d5b',
    storageBucket: 'gestor-notas-78d5b.firebasestorage.app',
    iosBundleId: 'com.example.ldsw37BasesDeDatos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBevhnB7WArQl6rMA2CJg9ITZxMrwdo-bo',
    appId: '1:826620575400:web:5e02447b39809282a1cc9d',
    messagingSenderId: '826620575400',
    projectId: 'gestor-notas-78d5b',
    authDomain: 'gestor-notas-78d5b.firebaseapp.com',
    storageBucket: 'gestor-notas-78d5b.firebasestorage.app',
  );
}
